name: generate-release

on:
  push:
    branches:
      - master

jobs:
  generate_release:
    runs-on: ubuntu-latest
    name: Generate release
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Build docker image
      run: |
          docker/build.sh cheats-box
    - name: Generate PDF
      run: |
          docker run                             \
              --rm                               \
              --volume $PWD:/workspace/cheats.rs \
              --cap-add=SYS_ADMIN                \
              cheats-box ./generate_pdf.sh cheats.rs/rust_cheat_sheet.pdf
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest-release"
        prerelease: false
        title: "Latest Release"
        files: rust_cheat_sheet.pdf
