name: generate-release

# FIXME: once we deploy this action only be sensitive to master branch
on: [push]
#on:
#  push:
#    branches:
#      - master

jobs:
  generate_release:
    runs-on: ubuntu-latest
    name: Generate release
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Build docker image
      run: |
          docker/build.sh cheats-box
    - name: Generate PDF
      run: |
          docker run                             \
              --rm                               \
              --volume $PWD:/workspace/cheats.rs \
              cheats-box ./generate_pdf.sh cheats.rs/rust_cheat_sheet.pdf
    - name: Generate current time stamp
      id: time
      run: |
          echo "::set-output name=now::$(date +'%Y-%m-%d-%H%M%S')"
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.time.outputs.now }}
        release_name: PDF ${{ steps.time.outputs.now }}
    - name: Upload PDF asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./rust_cheat_sheet.pdf
        asset_name: rust_cheat_sheet.pdf
        asset_content_type: application/pdf
